title: "Jana Learns"
email: ""
description: >-
  A learning journal about everything I figure out as a Dev Degree intern.
baseurl: "/jana-blog"
url: ""
github_username: janahussien

plugins:
  - jekyll-feed
